name: aurastate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^17.4.0
  linear_progress_bar: ^3.0.0
  smooth_page_indicator: ^2.0.1
  flutter_svg: ^2.3.0
  pinput: ^6.0.2
  dart_either: ^2.1.0
  shared_preferences: ^2.5.5
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
  


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/svg/

  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter/Inter_28pt-Regular.ttf
      - asset: assets/fonts/Inter/Inter_28pt-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter/Inter_28pt-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter/Inter_28pt-Bold.ttf
        weight: 700

  - family: PlayfairDisplay
    fonts:
      - asset: assets/fonts/Playfair Display/PlayfairDisplay-Regular.ttf
      - asset: assets/fonts/Playfair Display/PlayfairDisplay-Medium.ttf
        weight: 500
      - asset: assets/fonts/Playfair Display/PlayfairDisplay-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Playfair Display/PlayfairDisplay-Bold.ttf
        weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_only.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo_only.png"