// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB61TXOZLlgWYxdtygD03wr0wGRlIzsRC8',
    appId: '1:75660776334:web:166e729287bb95f9fc4adf',
    messagingSenderId: '75660776334',
    projectId: 'aurastate-app',
    authDomain: 'aurastate-app.firebaseapp.com',
    storageBucket: 'aurastate-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAaV4fyz_MQGQSN7vk25FVAznVUvMUKM8',
    appId: '1:75660776334:android:be171ede12bb9692fc4adf',
    messagingSenderId: '75660776334',
    projectId: 'aurastate-app',
    storageBucket: 'aurastate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtqEJyQxmGQCHaLNhQrhRipDS_SgHO-w',
    appId: '1:75660776334:ios:a5725b371ffcd700fc4adf',
    messagingSenderId: '75660776334',
    projectId: 'aurastate-app',
    storageBucket: 'aurastate-app.firebasestorage.app',
    iosBundleId: 'com.example.aurastate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFtqEJyQxmGQCHaLNhQrhRipDS_SgHO-w',
    appId: '1:75660776334:ios:a5725b371ffcd700fc4adf',
    messagingSenderId: '75660776334',
    projectId: 'aurastate-app',
    storageBucket: 'aurastate-app.firebasestorage.app',
    iosBundleId: 'com.example.aurastate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB61TXOZLlgWYxdtygD03wr0wGRlIzsRC8',
    appId: '1:75660776334:web:fec7a28e6191cf01fc4adf',
    messagingSenderId: '75660776334',
    projectId: 'aurastate-app',
    authDomain: 'aurastate-app.firebaseapp.com',
    storageBucket: 'aurastate-app.firebasestorage.app',
  );
}
